baseURL = "https://modest-colden-86b261.netlify.app/"
title = "Abolitionist Library Association"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Abolitionist Library Association"
description = "ABLA's website"
keywords = "abolition, libraries, library workers, activism"
# info = "Full Stack DevOps and Magician"
avatarURL = "images/avatar.png"
#gravatar = "john.doe@example.com"
# footerContent = "Enter a text here."
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = false
hideCopyright = false
since = 2019
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = []
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
prefetchsrc = ["'self'"]
# connect-src directive â€“ defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# [[params.social]]
# name = "Github"
# icon = "fa fa-github"
# weight = 1
# url = "https://github.com/johndoe/"

#[[params.social]]
# name = "Gitlab"
# icon = "fa fa-gitlab"
# weight = 2
# url = "https://gitlab.com/johndoe/"

[[params.social]]
# name = "Twitter"
# icon = "fa fa-twitter"
# weight = 3
# url = "https://twitter.com/johndoe/"

[[params.social]]
# name = "LinkedIn"
# icon = "fa fa-linkedin"
# weight = 4
# url = "https://www.linkedin.com/in/johndoe/"

[[params.social]]
# name = "Medium"
# icon = "fa fa-medium"
# weight = 5
# url = "https://medium.com/@johndoe"

[[params.social]]
# name = "RSS"
# icon = "fa fa-rss"
# weight = 6
# url = "https://myhugosite.com/index.xml"
# rel = "alternate"
# type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Get Involved"
weight = 2
url = "getinvolved/"

[[languages.en.menu.main]]
name = "Abolition 101"
weight = 3
url = "abolition101/"

[[languages.en.menu.main]]
name = "Resources"
weight = 4
url = "resources/"

# [[languages.en.menu.main]]
# name = "Banned Books"
# weight = 5
# url = "bannedbooks/"

# [[languages.en.menu.main]]
# name = "Events"
# weight = 6
# url = "events/"

